const countriesToCode = {
    Albania: 'AL',
    Kosovo: 'XK',
    Montenegro: 'ME',
    'North Macedonia': 'MK',
    Algeria: 'DZ',
    Bahrain: 'BH',
    Chad: 'TD',
    Comoros: 'KM',
    Djibouti: 'DJ',
    Egypt: 'EG',
    Eritrea: 'ER',
    Iraq: 'IQ',
    Israel: 'IL',
    Jordan: 'JO',
    Kuwait: 'KW',
    Lebanon: 'LB',
    Libya: 'LY',
    Mauritania: 'MR',
    Morocco: 'MA',
    Oman: 'OM',
    Qatar: 'QA',
    'Saudi Arabia': 'SA',
    Somalia: 'SO',
    'South Sudan': 'SS',
    Sudan: 'SD',
    Syria: 'SY',
    Tunisia: 'TN',
    Uganda: 'UG',
    'United Arab Emirates': 'AE',
    'Western Sahara': 'EH',
    Yemen: 'YE',
    Azerbaijan: 'AZ',
    'Bosnia and Herzegovina': 'BA',
    Bulgaria: 'BG',
    Belarus: 'BY',
    'Czech Republic': 'CZ',
    Argentina: 'AR',
    Austria: 'AT',
    Belize: 'BZ',
    Germany: 'DE',
    Hungary: 'HU',
    Italy: 'IT',
    Liechtenstein: 'LI',
    Switzerland: 'CH',
    Denmark: 'DK',
    Estonian: 'EE',
    Bolivia: 'BO',
    Chile: 'CL',
    Colombia: 'CO',
    'Costa Rica': 'CR',
    Cuba: 'CU',
    'Domican Republic': 'DO',
    'East Timor': 'TL',
    Ecuador: 'EC',
    'El Salvador': 'SV',
    'Equatorial Guinea': 'GQ',
    Guatemala: 'GT',
    Honduras: 'HN',
    Mexico: 'MX',
    Micronesia: 'FM',
    Nicaragua: 'NI',
    Panama: 'PA',
    Paraguay: 'PY',
    Peru: 'PE',
    Spain: 'ES',
    'United States': 'US',
    Uruguay: 'UY',
    Venezuela: 'VE',
    Finland: 'FI',
    Cyprus: 'CY',
    Greece: 'GR',
    Croatia: 'HR',
    Romania: 'RO',
    Slovakia: 'SK',
    Indonesia: 'ID',
    India: 'IN',
    Afghanistan: 'AF',
    Iran: 'IR',
    Monaco: 'MC',
    'San Marino': 'SM',
    'Vatican City': 'VA',
    'North Korea': 'KP',
    'South Korea': 'KR',
    Kazakhstan: 'KZ',
    Lithuania: 'LT',
    Latvia: 'LV',
    Brunei: 'BN',
    Malaysia: 'MY',
    Singapore: 'SG',
    Belgium: 'BE',
    Netherlands: 'NL',
    Suriname: 'SR',
    Norway: 'NO',
    Palau: 'PW',
    Palestine: 'PS',
    Philippines: 'PH',
    Poland: 'PL',
    Andorra: 'AD',
    Angola: 'AO',
    Brazil: 'BR',
    'Cape Verde': 'CV',
    'Guinea-Bissau': 'GW',
    Luxembourg: 'LU',
    Mozambique: 'MZ',
    Myanmar: 'MM',
    Portugal: 'PT',
    'Sao Tom and Principe': 'ST',
    Moldova: 'MD',
    Serbia: 'RS',
    Kyrgyzstan: 'KG',
    Mongolia: 'MN',
    Russia: 'RU',
    Turkmenistan: 'TM',
    Ukraine: 'UA',
    Uzbekistan: 'UZ',
    Sweden: 'SE',
    Slovenia: 'SI',
    Thailand: 'TH',
    Turkey: 'TR',
    'Antigua and Barbuda': 'AG',
    Australia: 'AU',
    Bahamas: 'BS',
    Barbados: 'BB',
    Cameroon: 'CM',
    Canada: 'CA',
    Dominica: 'DM',
    Eswatini: 'SZ',
    Ethopia: 'ET',
    Fiji: 'FJ',
    Grenada: 'GD',
    Guyana: 'GY',
    Iceland: 'IS',
    Ireland: 'IE',
    Jamaica: 'JM',
    Kenya: 'KE',
    Kiribati: 'KI',
    Laos: 'LA',
    Lesotho: 'LS',
    Liberia: 'LR',
    Madagascar: 'MG',
    Malawi: 'MW',
    Maldives: 'MV',
    Malta: 'MT',
    'New Zealand': 'NZ',
    Nigeria: 'NG',
    Pakistan: 'PK',
    'Papua New Guinea': 'PG',
    'St. Kitts and Nevis': 'KN',
    'St. Lucia': 'LC',
    Samoa: 'WS',
    Seychelles: 'SC',
    'Sierra Leona': 'SL',
    'South Africa': 'ZA',
    'Sri Lanka': 'LK',
    Tanzania: 'TZ',
    Tonga: 'TO',
    'Trinidad and Tobago': 'TT',
    Tuvalu: 'TV',
    'United Kingdom': 'GB',
    Vietnam: 'VN',
    Zimbabwe: 'ZW',
    Tajiktan: 'TJ',
    Benin: 'BJ',
    'Burkina Faso': 'BF',
    Burundi: 'BI',
    'Central African Republic': 'CF',
    'Republic of the Congo': 'CG',
    'Democratic Republic of the Congo': 'CD',
    "Cte d'lvoire": 'CI',
    France: 'FR',
    Gabon: 'GA',
    Gambia: 'GM',
    Guinea: 'GN',
    Haiti: 'HT',
    Mali: 'ML',
    Mauritius: 'MU',
    Niger: 'NE',
    Senegal: 'SN',
    Togo: 'TG',
    Armenia: 'AM',
    'Cape Verde': 'CV',
    Rwanda: 'RW'
};

const countryToCode = (country) => {
    return countriesToCode[country];
};
export default countryToCode;

const countries = [
    'Albania',
    'Kosovo',
    'Montenegro',
    'North Macedonia',
    'Algeria',
    'Bahrain',
    'Chad',
    'Comoros',
    'Djibouti',
    'Egypt',
    'Eritrea',
    'Iraq',
    'Israel',
    'Jordan',
    'Kuwait',
    'Lebanon',
    'Libya',
    'Mauritania',
    'Morocco',
    'Oman',
    'Qatar',
    'Saudi Arabia',
    'Somalia',
    'South Sudan',
    'Sudan',
    'Syria',
    'Tunisia',
    'Uganda',
    'United Arab Emirates',
    'Western Sahara',
    'Yemen',
    'Azerbaijan',
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Belarus',
    'Czech Republic',
    'Argentina',
    'Austria',
    'Belize',
    'Germany',
    'Hungary',
    'Italy',
    'Liechtenstein',
    'Switzerland',
    'Denmark',
    'Estonian',
    'Bolivia',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Cuba',
    'Domican Republic',
    'East Timor',
    'Ecuador',
    'El Salvador',
    'Equatorial Guinea',
    'Guatemala',
    'Honduras',
    'Mexico',
    'Micronesia',
    'Nicaragua',
    'Panama',
    'Paraguay',
    'Peru',
    'Spain',
    'United States',
    'Uruguay',
    'Venezuela',
    'Cyprus',
    'Greece',
    'Croatia',
    'Slovakia',
    'Indonesia',
    'India',
    'Afghanistan',
    'Iran',
    'Monaco',
    'San Marino',
    'Vatican City',
    'North Korea',
    'South Korea',
    'Kazakhstan',
    'Lithuania',
    'Latvia',
    'Brunei',
    'Malaysia',
    'Singapore',
    'Belgium',
    'Netherlands',
    'Suriname',
    'Norway',
    'Palau',
    'Palestine',
    'Philippines',
    'Poland',
    'Andorra',
    'Angola',
    'Brazil',
    'Cape Verde',
    'Guinea-Bissau',
    'Luxembourg',
    'Mozambique',
    'Myanmar',
    'Portugal',
    'Sao Tom and Principe',
    'Moldova',
    'Romania',
    'Serbia',
    'Kyrgyzstan',
    'Mongolia',
    'Russia',
    'Turkmenistan',
    'Ukraine',
    'Uzbekistan',
    'Finland',
    'Sweden',
    'Slovenia',
    'Thailand',
    'Turkey',
    'Antigua and Barbuda',
    'Australia',
    'Bahamas',
    'Barbados',
    'Cameroon',
    'Canada',
    'Dominica',
    'Eswatini',
    'Ethopia',
    'Fiji',
    'Grenada',
    'Guyana',
    'Iceland',
    'Ireland',
    'Jamaica',
    'Kenya',
    'Kiribati',
    'Laos',
    'Lesotho',
    'Liberia',
    'Madagascar',
    'Malawi',
    'Maldives',
    'Malta',
    'New Zealand',
    'Nigeria',
    'Pakistan',
    'Papua New Guinea',
    'St. Kitts and Nevis',
    'St. Lucia',
    'Samoa',
    'Seychelles',
    'Sierra Leona',
    'South Africa',
    'Sri Lanka',
    'Tanzania',
    'Tonga',
    'Trinidad and Tobago',
    'Tuvalu',
    'United Kingdom',
    'Vietnam',
    'Zimbabwe',
    'Tajiktan',
    'Benin',
    'Burkina Faso',
    'Burundi',
    'Central African Republic',
    'Republic of the Congo',
    'Democratic Republic of the Congo',
    "Cte d'lvoire",
    'France',
    'Gabon',
    'Gambia',
    'Guinea',
    'Haiti',
    'Mali',
    'Mauritius',
    'Niger',
    'Senegal',
    'Togo',
    'Armenia',
    'Cape Verde',
    'Rwanda'
];

export default countries;


const codeToCountries = {
    al: ['Albania', 'Kosovo', 'Montenegro', 'North Macedonia'],
    ar: [
        'Algeria',
        'Bahrain',
        'Chad',
        'Comoros',
        'Djibouti',
        'Egypt',
        'Eritrea',
        'Iraq',
        'Israel',
        'Jordan',
        'Kuwait',
        'Lebanon',
        'Libya',
        'Mauritania',
        'Morocco',
        'Oman',
        'Qatar',
        'Saudi Arabia',
        'Somalia',
        'South Sudan',
        'Sudan',
        'Syria',
        'Tanzania',
        'Tunisia',
        'Uganda',
        'United Arab Emirates',
        'Western Sahara',
        'Yemen'
    ],
    az: ['Azerbaijan'],
    ba: ['Bosnia and Herzegovina', 'Montenegro'],
    bg: ['Bulgaria'],
    by: ['Belarus'],
    cz: ['Czech Republic'],
    de: ['Argentina', 'Austria', 'Belize', 'Germany', 'Hungary', 'Italy', 'Liechtenstein', 'Switzerland'],
    dk: ['Denmark', 'Germany'],
    ee: ['Estonian'],
    es: [
        'Argentina',
        'Belize',
        'Bolivia',
        'Chile',
        'Colombia',
        'Costa Rica',
        'Cuba',
        'Domican Republic',
        'East Timor',
        'Ecuador',
        'El Salvador',
        'Equatorial Guinea',
        'Guatemala',
        'Honduras',
        'Mexico',
        'Micronesia',
        'Nicaragua',
        'Panama',
        'Paraguay',
        'Peru',
        'Spain',
        'United States',
        'Uruguay',
        'Venezuela',
        'Western Sahara'
    ],
    fi: ['Finland'],
    gr: ['Cyprus', 'Greece'],
    hr: ['Bosnia and Herzegovina', 'Croatia'],
    hu: ['Hungary', 'Romania', 'Slovakia'],
    id: ['Indonesia'],
    il: ['Israel'],
    in: ['India', 'United Arab Emirates'],
    ir: ['Afghanistan', 'Iran'],
    it: ['Argentina', 'Italy', 'Libya', 'Monaco', 'San Marino', 'Switzerland', 'Vatican City'],
    kr: ['North Korea', 'South Korea'],
    kz: ['Kazakhstan'],
    la: ['Vatican City'],
    lt: ['Lithuania'],
    lv: ['Latvia'],
    mk: ['North Macedonia'],
    my: ['Brunei', 'Malaysia', 'Singapore'],
    nl: ['Belgium', 'Netherlands', 'Suriname'],
    no: ['Norway'],
    ph: ['Palau', 'Palestine', 'Philippines'],
    pl: ['Lithuania', 'Poland'],
    pt: [
        'Andorra',
        'Angola',
        'Brazil',
        'Cape Verde',
        'Guinea-Bissau',
        'Luxembourg',
        'Mozambique',
        'Myanmar',
        'Portugal',
        'Sao Tom and Principe'
    ],
    ro: ['Moldova', 'Romania'],
    rs: ['Bosnia and Herzegovina', 'Montenegro', 'Serbia'],
    ru: [
        'Belarus',
        'Estonian',
        'Kazakhstan',
        'Kyrgyzstan',
        'Latvia',
        'Lithuania',
        'Moldova',
        'Mongolia',
        'Russia',
        'Turkmenistan',
        'Ukraine',
        'Uzbekistan'
    ],
    se: ['Finland', 'Sweden'],
    si: ['Slovenia'],
    sk: ['Slovakia'],
    th: ['Malaysia', 'Thailand'],
    tr: ['Bulgaria', 'Turkey'],
    ua: ['Ukraine'],
    us: [
        'Afghanistan',
        'Antigua and Barbuda',
        'Argentina',
        'Australia',
        'Bahrain',
        'Bahamas',
        'Barbados',
        'Belize',
        'Brunei',
        'Cameroon',
        'Canada',
        'Cape Verde',
        'Chile',
        'Costa Rica',
        'Dominica',
        'Egypt',
        'Eritrea',
        'Eswatini',
        'Ethopia',
        'Fiji',
        'Grenada',
        'Guyana',
        'Hungary',
        'Iceland',
        'Indonesia',
        'Ireland',
        'Israel',
        'Jamaica',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'South Korea',
        'Kuwait',
        'Laos',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Malta',
        'Monaco',
        'Netherlands',
        'New Zealand',
        'Nigeria',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestine',
        'Panama',
        'Papua New Guinea',
        'Philippines',
        'Qatar',
        'St. Kitts and Nevis',
        'St. Lucia',
        'Samoa',
        'So Tom and Principe',
        'Seychelles',
        'Sierra Leona',
        'Singapore',
        'South Africa',
        'South Sudan',
        'Sri Lanka',
        'Sudan',
        'Suriname',
        'Switzerland',
        'Syria',
        'Tanzania',
        'Tonga',
        'Trinidad and Tobago',
        'Tuvalu',
        'Uganda',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Vietnam',
        'Zimbabwe'
    ],
    uz: ['Afghanistan', 'Kyrgyzstan', 'Tajiktan', 'Turkmenistan', 'Uzbekistan'],
    fr: [
        'Algeria',
        'Andorra',
        'Belgium',
        'Benin',
        'Burkina Faso',
        'Burundi',
        'Cameroon',
        'Canada',
        'Central African Republic',
        'Chad',
        'Comoros',
        'Democratic Republic of the Congo',
        'Republic of the Congo',
        "Cte d'lvoire",
        'Djibouti',
        'Dominica',
        'Egypt',
        'France',
        'Gabon',
        'Gambia',
        'Grenada',
        'Guinea',
        'Haiti',
        'Laos',
        'Lebanon',
        'Luxembourg',
        'Madagascar',
        'Mali',
        'Mauritania',
        'Mauritius',
        'Monaco',
        'Morocco',
        'Niger',
        'Sao Tom and Principe',
        'Senegal',
        'Switzerland',
        'Syria',
        'Togo',
        'Tunisia',
        'Vatican City',
        'Vietnam',
        'Western Sahara'
    ],
    ct: ['Andorra', 'France', 'Spain'],
    am: ['Armenia', 'Lebanon'],
    cv: ['Cape Verde'],
    is: ['Iceland'],
    ku: ['Iran', 'Iraq', 'Syria', 'Turkey'],
    np: ['Italy'],
    pj: ['Pakistan'],
    sw: [
        'Comoros',
        'Democratic Republic of the Congo',
        'Republic of the Congo',
        'Kenya',
        'Rwanda',
        'Tanzania',
        'Uganda'
    ],
    tt: ['Russia'],
    vt: ['Vietnam']
};
export default codeToCountries;
