// used for searching if code is in list set.has()
const languageCodesSet = new Set([
    'us',
    'es',
    'ru',
    'de',
    'fr',
    'tr',
    'it',
    'pt',
    'kr',
    'gr',
    'ar',
    'rs',
    'fi',
    'ro',
    'se',
    'ir',
    'pl',
    'hr',
    'il',
    'bg',
    'hu',
    'al',
    'ua',
    'dk',
    'cz',
    'ba',
    'no',
    'ct',
    'nl',
    'in',
    'ku',
    'az',
    'uz',
    'id',
    'lv',
    'la',
    'ee',
    'sk',
    'cv',
    'np',
    'kz',
    'mk',
    'ph',
    'si',
    'lt',
    'is',
    'vt',
    'th',
    'am',
    'sw',
    'pj',
    'by',
    'my',
    'tt'
]);

export { languageCodesSet }

// used for accessing an ordered list of languages array.forEach
const languageStringsArray = [
    'Albanian',
    'Arabic',
    'Armenian',
    'Azerbaijani',
    'Belarusian',
    'Bosnian',
    'Bulgarian',
    'Cape Verdean',
    'Catalan',
    'Croatian',
    'Czech',
    'Danish',
    'Dutch',
    'English',
    'Estonian',
    'Filipino',
    'Finnish',
    'French',
    'German',
    'Greek',
    'Hebrew',
    'Hindi',
    'Hungarian',
    'Icelandic',
    'Indonesian',
    'Italian',
    'Kazakh',
    'Korean',
    'Kurdish',
    'Latin',
    'Latvian',
    'Lithuanian',
    'Macedonian',
    'Malay',
    'Neapolitan',
    'Norwegian',
    'Persian',
    'Polish',
    'Portuguese',
    'Punjabi',
    'Romanian',
    'Russian',
    'Serbian',
    'Slovak',
    'Slovenian',
    'Spanish',
    'Swahili',
    'Swedish',
    'Tatar',
    'Thai',
    'Turkish',
    'Ukrainian',
    'Uzbek',
    'Vietnamese'
]

export { languageStringsArray };

// used for searching if language is in list set.has()
const languagesStringsSet = new Set([
    'albanian',
    'arabic',
    'armenian',
    'azerbaijani',
    'belarusian',
    'bosnian',
    'bulgarian',
    'cape Verdean',
    'catalan',
    'croatian',
    'czech',
    'danish',
    'dutch',
    'english',
    'estonian',
    'filipino',
    'finnish',
    'french',
    'german',
    'greek',
    'hebrew',
    'hindi',
    'hungarian',
    'icelandic',
    'indonesian',
    'italian',
    'kazakh',
    'korean',
    'kurdish',
    'latin',
    'latvian',
    'lithuanian',
    'macedonian',
    'malay',
    'neapolitan',
    'norwegian',
    'persian',
    'polish',
    'portuguese',
    'punjabi',
    'romanian',
    'russian',
    'serbian',
    'slovak',
    'slovenian',
    'spanish',
    'swahili',
    'swedish',
    'tatar',
    'thai',
    'turkish',
    'ukrainian',
    'uzbek',
    'vietnamese'
])

export { languagesStringsSet };

const isOfferedLanguage = (languageString) => {
    return languagesStringsSet.has(languageString);
}

export { isOfferedLanguage }

const codeToLanguage = {
    al: 'Albanian',
    ar: 'Arabic',
    az: 'Azerbaijani',
    ba: 'Bosnian',
    bg: 'Bulgarian',
    by: 'Belarusian',
    cz: 'Czech',
    de: 'German',
    dk: 'Danish',
    ee: 'Estonian',
    es: 'Spanish',
    fi: 'Finnish',
    gr: 'Greek',
    hr: 'Croatian',
    hu: 'Hungarian',
    id: 'Indonesian',
    il: 'Hebrew',
    in: 'Hindi',
    ir: 'Persian',
    it: 'Italian',
    kr: 'Korean',
    kz: 'Kazakh',
    la: 'Latin',
    lt: 'Lithuanian',
    lv: 'Latvian',
    mk: 'Macedonian',
    my: 'Malay',
    nl: 'Dutch',
    no: 'Norwegian',
    ph: 'Filipino',
    pl: 'Polish',
    pt: 'Portuguese',
    ro: 'Romanian',
    rs: 'Serbian',
    ru: 'Russian',
    se: 'Swedish',
    si: 'Slovenian',
    sk: 'Slovak',
    th: 'Thai',
    tr: 'Turkish',
    ua: 'Ukrainian',
    us: 'English',
    uz: 'Uzbek',
    fr: 'French',
    ct: 'Catalan',
    am: 'Armenian',
    cv: 'Cape Verdean',
    is: 'Icelandic',
    ku: 'Kurdish',
    np: 'Neapolitan',
    pj: 'Punjabi',
    sw: 'Swahili',
    tt: 'Tatar',
    vt: 'Vietnamese'
};
export { codeToLanguage }

const languageCodes = [
    'al',
    'am',
    'ar',
    'az',
    'ba',
    'bg',
    'by',
    'ct',
    'cv',
    'cz',
    'de',
    'dk',
    'ee',
    'es',
    'fi',
    'fr',
    'gr',
    'hr',
    'hu',
    'id',
    'il',
    'in',
    'ir',
    'is',
    'it',
    'kr',
    'ku',
    'kz',
    'la',
    'lt',
    'lv',
    'mk',
    'my',
    'nl',
    'no',
    'np',
    'ph',
    'pj',
    'pl',
    'pt',
    'ro',
    'rs',
    'ru',
    'se',
    'si',
    'sk',
    'sw',
    'th',
    'tr',
    'tt',
    'ua',
    'us',
    'uz',
    'vt',]

export { languageCodes }